- cypress.config.js
- cypress/fixtures/api_addcategories.json
- cypress/fixtures/api_approveallfeatures.json
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
Added new 4 API test cases for Automate.
> Automated 4 API of FE / CreatefeaturewithAI/ApproveAllfeature/Createcategories/DeleteCategories

- cypress.config.js
- cypress/fixtures/api_addFeatureManually.json
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
> Automated 4 new test cases of PRD /putprd_ai_features/patchprd_ai_features/deleteprd_ai_features/putprd_ai_categories/

- cypress.config.js
- cypress/fixtures/api_addBugtask.json
- cypress/fixtures/api_createApp.json
- cypress/fixtures/api_createAttributes.json
- cypress/fixtures/api_login.json
- cypress/fixtures/api_updateWithPatchBugtask.json
- cypress/fixtures/api_updateWithPutBugtask.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/CatalogPageTest.js
- cypress/integration/api/tests/dashboardtest.js
I have Automated 6 Apis which is belongs to Bug Task and all endpoint are given below.
1. GetBugTaskList  - "/api/v1/apps/{apk}/bug-tasks/".
2. CreateBugTask- "/api/v1/apps/{apk}/bug-tasks/".
3. GetBugTaskById - "/api/v1/apps/{apk}/bug-tasks/{id}".
4. PutBugTask -  "/api/v1/apps/{apk}/bug-tasks/{id}".
5. PatchBugTask -  "/api/v1/apps/{apk}/bug-tasks/{id}".
6. DeleteBugTask -  "/api/v1/apps/{apk}/bug-tasks/{id}".
> Bug Task Api automated

- cypress.config.js
- cypress/integration/api/pages/ConnectorsPage.js
- cypress/integration/api/tests/ConnectorsPageTest.js
/api/v2/apps/{app_pk}/connectors/{id}/
> apps connector update

- cypress.config.js
- cypress/fixtures/api_addFile.json
- cypress/fixtures/api_updateWithPatchFile.json
- cypress/fixtures/api_updateWithPutFile.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
I have Automated 5 Apis and updated 1 Apis all endpoints are given below.
1. GetFilesList = "/api/v1/apps/{apk}/files".
2. CreateFile =  "/api/v1/apps/{apk}/files".
3. GetFileUsingId = "/api/v1/apps/{apk}/files/{id}/.
4. PutFile = "/api/v1/apps/{apk}/files/{id}/.
5. PatchFile = "/api/v1/apps/{apk}/files/{id}/.
6. DeleteFile = "/api/v1/apps/{apk}/files/{id}/.
> File Automation Code

- cypress.config.js
- cypress/fixtures/api_createStudio_Screen.json
- cypress/integration/api/pages/StudioPage.js
- cypress/integration/api/tests/StudioPageTest.js
getStudiopage1:"/api/v2/apps/",
getStudiopage2:"/",
> Navigates  to Studiolanding Page. Get :- getStudiopage1:"/api/v2/apps/",

- cypress.config.js
- cypress/integration/api/pages/ConnectorsPage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/ConnectorsPageTest.js
- cypress/integration/api/tests/PrdPageTest.js
1.GET-prd_list:- /api/v1/apps/{app_pk}/prd/
2.PATCH-prd_partial_update:- /api/v1/apps/{app_pk}/prd/
> GET prd_List, PATCH prd_Partial_Update

- cypress/integration/api/pages/CatalogPage.js
- cypress/integration/api/tests/CatalogPageTest.js
GET | /api/v1/apps/{app_pk}/edges/
POST | /api/v1/apps/{app_pk}/edges/
GET | /api/v1/apps/{app_pk}/edges/{id}/
PUT | /api/v1/apps/{app_pk}/edges/{id}/
PATCH | /api/v1/apps/{app_pk}/edges/{id}/
DELETE | /api/v1/apps/{app_pk}/edges/{id}/
> Changes done

- cypress.config.js
- cypress/fixtures/api_post_Modules_Create.json
- cypress/integration/api/pages/ModulePage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/ModulePageTest.js
- cypress/integration/api/tests/PrdPageTest.js
getattachmentslist:"/api/v1/attachments/",
getmoduleslist1: "/api_v2_apps_modules_list/",
getmoduleslist2: "/",
postCreatemodules1 :"/api/v2/apps/",
postCreatemodules2 :"/modules/",
> Added Module List, Modules Create and Attachment API's

- cypress.config.js
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
Api automated-
GET - /api/v2/certifications/
POST- /api/v2/certifications/
GET- /api/v2/certifications/{id}/
PUT-/api/v2/certifications/{id}/
PATCH-/api/v2/certifications/{id}/
DELETE- /api/v2/certifications/{id}/
> Api for Certifications GET, POST,GET, PUT, PATCH,DELETE

- cypress.config.js
New URL - https://crowdbotics-slack-dev.crowdbotics.com/ (Updated in our automation script)
> As per the new URL changes, URL updated from automation script

- cypress.config.js
- cypress/integration/api/pages/CatalogPage.js
- cypress/integration/api/pages/ModulePage.js
- cypress/integration/api/tests/CatalogPageTest.js
> Fixed failed API test cases

- cypress.config.js
- cypress/integration/api/pages/JobPage.js
- cypress/integration/api/tests/JobPageTest.js
Automated 2 APIs test case-
1. GET - /api/v2/candidates/
2. GET - /api/v2/candidates/{id}/
Fixed 2 test cases-
1. doPutJobtype
2. doDeleteJobtypeByid
> Added APIs test case for Candidate and fixed 2 test cases in Job Type

- cypress.config.js
- cypress/fixtures/api_patch_cbusers.json
- cypress/fixtures/api_post_cbusers.json
- cypress/fixtures/api_put_cbusers.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
5 api added for CB users
1. Get - /api/v2/cb-users/
2. Post- /api/v2/cb-users/
3. Get - /api/v2/cb-users/{id}/
4. Put- /api/v2/cb-users/{id}/
5. Patch-/api/v2/cb-users/{id}/
> Added API test cases for CB user.

- cypress.config.js
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
- cypress/integration/api/tests/dashboardtest.js
Automated 5 API's test cases - 
1. -  get/api/v2/roles/
2. - get/api/v2/reports/
3. - get/api/v1/developer_requests/
4. - /api/v1/developer_requests/ ID
5. -  getResponses
> Added API's test cases for Reports and responses & user

- cypress.config.js
- cypress/fixtures/api_addCliFeedback.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/pages/StudioPage.js
- cypress/integration/api/tests/PrdPageTest.js
- cypress/integration/api/tests/StudioPageTest.js
- cypress/integration/api/tests/dashboardtest.js
Automated 4 New API's test cases - 
1- "/api/v2/project_clones/",
2- "/api/v2/project_clones/",
3-  "/api/v2/cli-feedback/",
4- "/api/v2/robots/openai/status",
> Added API's test cases for Project-clones & Open-AI and CLI

- cypress.config.js
- cypress/fixtures/api_add_slides.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/pages/ModulePage.js
- cypress/integration/api/tests/ModulePageTest.js
- cypress/integration/api/tests/dashboardtest.js
Apis added-
1. Get API Reports - /api/v2/apps/{app_pk)/reports/
2. Get API Slides - /api/v2/apps/{app_pk)/slideshow/
3. Post API Slide -   /api/v2/apps/{app_pk)/slideshow/
> New test case added for slides and reports

- cypress.config.js
- cypress/fixtures/api_addShareableconnectors.json
- cypress/fixtures/api_add_Certificaionsdata.json
- cypress/fixtures/api_patchCertifications.json
- cypress/fixtures/api_patch_cbusers.json
- cypress/fixtures/api_post_cbusers.json
- cypress/fixtures/api_putCertifications.json
- cypress/fixtures/api_put_cbusers.json
- cypress/fixtures/api_updateWithPutFile.json
- cypress/integration/api/pages/ConnectorsPage.js
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
- cypress/integration/api/tests/dashboardtest.js
Automated 2 New API's And Fixed 37 test cases of different files and commented some invalid test cases
1. - /mobile-builds/
2. - /api/v1/resend-verification/
> Added API's test cases for Mobilebuilds & resend verifications and fixed test cases 

- cypress.config.js
- cypress/fixtures/api_addMagiclink.json
- cypress/fixtures/api_addPostfeedback.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
> Added API's Test Cases for Dashboard feedback, Social APP

- cypress.config.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
Automated new 3 API's test cases
> Added API's test cases for Demo phase & demo roles & demo ticket

- cypress.config.js
- cypress/fixtures/api_CatalogLogin.json
- cypress/fixtures/api_ConnectorLogin.json
- cypress/fixtures/api_DashboardLogin.json
- cypress/fixtures/api_DatamodelLogin.json
- cypress/fixtures/api_JobLogin.json
- cypress/fixtures/api_PrdLogin.json
- cypress/fixtures/api_SettingLogin.json
- cypress/fixtures/api_StudioLogin.json
- cypress/fixtures/api_TaskLogin.json
- cypress/fixtures/api_TeammemberLogin.json
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/pages/loginPage.js
- cypress/integration/api/tests/dashboardtest.js
- cypress/integration/api/tests/logintest.js
Automated 2 API's for project logs and fixed login flow in all module files.
> Added API's for project logs and fixed login flow in all module files

- cypress.config.js
- cypress/fixtures/api_post_cancel_deployments.json
- cypress/fixtures/api_post_deployments.json
- cypress/integration/api/pages/SettingsPage.js
- cypress/integration/api/tests/SettingsPageTest.js
2 APIs added -
POST - /api/v2/apps/{ID}/deploy/
POST- /api/v2/apps/{ID}/cancel/deploy/
> Post Deployment/ Cancel apis

- cypress/fixtures/api_addCatalogModule.json
- cypress/fixtures/api_updateWithPatchCatalogModule.json
- cypress/fixtures/api_updateWithPutCatalogModule.json
I have fixed the API related to the Catalog. Please review and merge it. If you notice any issues, please let me know. Thanks.
> Fixed Test cases for Catalog module.

- cypress.config.js
- cypress/fixtures/api_add_code_packages.json
- cypress/fixtures/api_patchCodePackages_new.json
- cypress/fixtures/api_putCodePackages_new.json
- cypress/integration/api/pages/DocumentPage.js
- cypress/integration/api/tests/DocumentPageTest.js
Hi Team,
I have automated five new APIs related to code packages functionality. Kindly review my PR and provide appropriate comments.
The following APIs have been automated with their respective HTTP methods:
GET - /api/v2/code_packages/ - Get all code packages
POST -  /api/v2/code_packages/ - Create a new code packages.
GET  - /api/v2/code_packages/{id} - Retrieve a code packages by ID.
PUT  - /api/v2/code_packages/{id} - Update a code packages by ID.
PATCH  - /api/v2/code_packages/{id} - Partially update a code packages by ID.
I have also attached a screenshot as an artifact to demonstrate the functionality.
> code_package

- cypress.config.js
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
Hi Team I have automated PRD Download related API so please check my PR and merge it.
> I have automated download pdf api please check my PR.

- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
All the API's were passing when we run the spec file but when we did parallel execution then some test cases were failed, So I fixed it.
> Fixed the NewPRDSpec file

- cypress.config.js
- cypress/integration/api/pages/CatalogPage.js
- cypress/integration/api/tests/CatalogPageTest.js
Hi team, I have made some API fixes in the catalog spec. Please review my code and merge it.
> Catalog API Issue Resolutions

- cypress.config.js
- cypress/fixtures/api_CreateJiraSetup.json
- cypress/fixtures/api_TeammemberLogin.json
- cypress/fixtures/api_patch_JiraSetup.json
- cypress/fixtures/api_put_JiraSetup.json
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
I have Automated 6 New PRD jirasetup test cases -
1- /api/v1/prd/{prd_pk}/jira_setup/
2-/api/v1/prd/{prd_pk}/jira_setup/
3-/api/v1/prd/{prd_pk}/jira_setup/{id}
4-/api/v1/prd/{prd_pk}/jira_setup/{id}
5-/api/v1/prd/{prd_pk}/jira_setup/{id}
6-/api/v1/prd/{prd_pk}/jira_setup/{id
> Automated 6 new API test cases

- cypress/integration/api/pages/loginPage.js
I have fixed some test cases in the module spec file. Please check my PR and merge it.
> module testcase fixes

- cypress.config.js
- cypress/fixtures/api_add_codeto_spec.json
- cypress/fixtures/api_add_put_Codeto_spec.json
- cypress/fixtures/api_patch_Codeto_spec.json
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
Automated 5 New Code to spec test cases - 
1- /api/v1/apps/{app_pk}/code-to-spec/start-code-spec/
2- /api/v1/apps/{app_pk}/code-to-spec/{id}/ Get
3- /api/v1/apps/{app_pk}/code-to-spec/{id}/ Put
4- /api/v1/apps/{app_pk}/code-to-spec/{id}/ Patch
5- /api/v1/apps/{app_pk}/code-to-spec/{id}/ Delete
> Automated 5 New Code to spec test cases

- cypress.config.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/PrdPageTest.js
Hi Team , I have automated one new API related to module deployment So Please review my PR and merge it.
> I have automated one API related to module deployment.

- cypress.config.js
- cypress/integration/api/pages/JobPage.js
- cypress/integration/api/pages/PrdPage.js
- cypress/integration/api/tests/JobPageTest.js
- cypress/integration/api/tests/PrdPageTest.js
Automated 3 New API test cases
1- /api/v1/apps/prd/{id}/update-proposal/
2-/api/v1/apps/prd/{id}/toggle-self-serve-estimation/
3-/api/v2/apps/pending-invitations/
> Automated 3 New API test cases

- cypress.config.js
- cypress/fixtures/api_addScreenAIJobs.json
- cypress/integration/api/pages/StudioPage.js
- cypress/integration/api/tests/StudioPageTest.js
1. get screen AI job (/api/v2/apps/{app_pk}/screens-ai/jobs/)
2. post screen AI job (/api/v2/apps/{app_pk}/screens-ai/jobs/)
3. get screen AI job by ID (/api/v2/apps/{app_pk}/screens-ai/jobs/{id}/)
> Added 3 new APIs 

- cypress.config.js
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
1. GET /api/v2/apps/{app_pk}/components/{id}/module-options/
2. POST /api/v2/apps/{app_pk}/components/{id}/module-options/
> Add new API's of Module Options

- cypress.config.js
- cypress/fixtures/api_updateAttribute.json
- cypress/fixtures/api_updateAttributePatch
- cypress/integration/api/pages/DashboardPage.js
- cypress/integration/api/tests/dashboardtest.js
PUT, PATCH & DELETE
/api/v2/apps/{app_pk}/attributes/{id}/
> Automated new test cases related to attributes

- cypress.config.js
- cypress/integration/api/pages/DocumentPage.js
- cypress/integration/api/tests/DocumentPageTest.js
I have automated some APIs related to the chatbot Questions. Please review and merge my PR.
> chatboat question 

- cypress.config.js
- cypress/integration/api/pages/DocumentPage.js
- cypress/integration/api/tests/DocumentPageTest.js
I have automated the API that retrieves the list of repositories for a specific user, as well as the list of apps created by those repositories. If you have time, could you please review my PR and merge it?
> I have automated the API related to the repository.

- cypress.config.js
- cypress/fixtures/api_add_Sendmessagetocopilot.json
- cypress/fixtures/api_add_Syncprdtocopilotagent.json
- cypress/fixtures/api_add_createloadprdintochat.json
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
> Automated 6 New API test cases of PRD Copilot

- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
> Done some changes

- cypress.config.js
- cypress/fixtures/api_patch_context_by_orguser.json
- cypress/fixtures/api_patch_specificgitconfig_by_org.json
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
I have automated some APIs related to git-config in this PR, and also fixed one Copilot API.
Please review my PR.
Artifact -
> APIs related to git config and context.

- cypress.config.js
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
I have automated some APIs related to organization members. Please review my PR.
> Organization Members

- cypress.config.js
- cypress/integration/api/pages/NewPrdPage.js
- cypress/integration/api/tests/NewPrdPageTest.js
Hi Team,
I have automated 4 new APIs related to metrics and repo.
Please review and merge.
> Matircs and Git-Repo

- cypress.config.js
- cypress/fixtures/api_c2s.json
- cypress/fixtures/api_create_app_with_repo_c2s.json
- cypress/integration/api/pages/C2SPage.js
- cypress/integration/api/pages/loginPage.js
- cypress/integration/api/tests/C2SPageTest.js
I have automated some APIs related to the C2S flow. If you have time, please review my PR and merge it.
> Create app with repo (C2S).

- cypress.config.js
- cypress/fixtures/api_create_C2S.json
- cypress/integration/api/pages/C2SPage.js
- cypress/integration/api/tests/C2SPageTest.js
I have automated six new apis related to C2S flow, If you have time please check my PR and merge it.
> C2S_Flow Automation.

- cypress.config.js
- cypress/integration/api/pages/C2SPage.js
- cypress/integration/api/tests/C2SPageTest.js
I have automated five new APIs related to the C2S flow, which cover the following endpoints:
1. /api/v1/c2s/{C2S_ID}/code/
2. /api/v1/c2s/{C2S_ID}/code/entry-points/
3. /api/v1/c2s/{C2S_ID}/code/file-path-status/
4. /api/v1/c2s/{C2S_ID}/code/files/
5. /api/v1/c2s/{C2S_ID}/requirements/business-logic/
If you have some time, please review and merge my PR. Thanks!
> I have automated 5 new APIs related to the C2S flow.

- cypress.config.js
- cypress/fixtures/api_Create_Kenobi_C2S_Private_Repo.json
- cypress/fixtures/api_Patch_Kenobi_C2S_Private_Repo.json
- cypress/fixtures/api_Put_Kenobi_C2S_Private_Repo.json
- cypress/integration/api/pages/KenobiPage.js
- cypress/integration/api/tests/KenobiPageTest.js
Hi Team,
I have successfully automated the following five Kenobi-related APIs (for private repositories):
Create Kenobi using a private repository
Retrieve Kenobi by ID using a private repository
Update (PUT) Kenobi by ID using a private repository
Partially update (PATCH) Kenobi by ID using a private repository
Delete Kenobi by ID using a private repository
Artifact -
> I have automated Kenobi related APIs.

- cypress/integration/api/pages/KenobiHealthCheckPage.js
- cypress/integration/api/tests/kenobi-health-check.test.js
- package-lock.json
- Add KenobiHealthCheckPage.js with 21 endpoint functions
- Add kenobi-health-check.test.js with comprehensive test suite
- Test coverage for Vector Store, Agent, Prompts, Code Analysis, Discovery, Graph Cache, PRD, Authentication, and Accuracy endpoints
- All tests passing successfully
- Follows existing code patterns from origin/kenobiPublic branch
> Add Kenobi API health check tests for 21 working GET endpoints
